[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/home"
  to = "/home.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
